1.How can you throw an exception object for exception?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>
  
<blockquote>
  
The exception object contains a lot of debugging information such as method hierarchy, line number where the exception occurred, type of exception, etc. When the exception occurs in a method, the process of creating the exception object and handing it over to the runtime environment is called "throwing an  exception".Once runtime receives the exception object, it tries to find the handler for the exception. Exception Handler is the block of code that can process the exception object.

</blockquote>
  
</details>

---

2.Explain throw keyword with real time example?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>
we might want to generate exceptions explicitly in our code, for example in a user authentication program we should throw exceptions to clients if the password is null. The throw keyword is used to throw exceptions to the runtime to handle it.

</blockquote>
  
</details>

---

3.How the exception condition is created?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>
  
An object representing that exception is created and thrown in the method that caused the error. That method may choose to handle the exception itself, or pass it on. Either way, at some point, the exception is caught and processed. Exceptions can be generated by the Java run-time system, or they can be manually generated by your code.

</blockquote>
  
</details>

---

4.How exception handling manages try,catch,throw,throws and finally statements?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

Program statements that you want to monitor for exceptions are contained within a try block. If an exception occurs within the try block, it is thrown. The code can catch this exception using catch and handle it in some rational manner.System-generated exceptions are automatically thrown by the Java run-time system. To manually throw an exception, use the keyword throw. Any exception that is thrown out of a method must be specified as such by a throws clause. Any code that absolutely must be executed after a try block completes is put in a finally block.

</blockquote>

</details>

---

5.How the StackOverflow occurred?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

Error, which defines exceptions that are not expected to be caught under normal circumstances by your program. Exceptions of type Error are used by the Java run-time system to indicate errors having to do with the run-time environment,itself. Stack overflow is an example of such an error

</blockquote>

</details>

---

6.Can we keep other statements in between ‘try’, ‘catch’, and ‘finally’ blocks?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

It is not necessary to include any statements between the  ‘try’, ‘catch’, and ‘finally’ blocks, since they form one whole unit of the exception handling mechanism.

</blockquote>

</details>

---

7.Can we  include only a ‘try’ block without the ‘catch’ and ‘finally’ blocks?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

This would result in compilation error. It is necessary for the ‘try’ block to be followed with either a ‘catch’ block or a ‘finally’ block, if not both. Either one of ‘catch’ or ‘finally’ blocks is needed so that the flow of exception handling is undisrupted.

</blockquote>

</details>

---

8.What happens when you don’t handle exceptions in your program.

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

All exception types are subclasses of the built-in class Throwable. Thus, Throwable is at the top of the exception class hierarchy. Immediately below Throwable are two subclasses that partition exceptions into two distinct branches. One branch is headed by Exception. This class is used for exceptional conditions that user programs should catch. This is also the class that you will subclass to create your own custom exception types. There is an important subclass of Exception, called RuntimeException. Exceptions of this type are automatically defined for the programs that you write and include things such as division by zero and invalid array indexing.The other branch is topped by Error, which defines exceptions that are not expected to be caught under normal circumstances by your program. Exceptions of type Error are used by the Java run-time system to indicate errors having to do with the run-time environment,itself. Stack overflow is an example of such an error.


</blockquote>

</details>

---

9.Can we keep the statements after the ‘finally’ block?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

When the Java run-time system detects a runtime-error, it constructs a new exception object and then throws the exception because once an exception has been thrown, it must be caught by an exception handler and dealt with immediately. If we didn't supplied any exception handlers of our own, the exception is caught by the default handler provided by the Java run-time system. Any exception that is not caught by your program will ultimately be processed bythe default handler. The default handler describes the exception and prints a stack trace from the point at which the exception occurred, and terminates the program.

</blockquote>

</details>

---

10.How can you differentiate NoClassDefFoundError and ClassNotFoundException in Java?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

This will result in an unreachable catch block error. This is because the control will be returning from the 'finally' block itself. The compiler will fail to execute the code after the line with the exception. That is why the execution will show an unreachable code error.

</blockquote>

</details>

---

11.Explain the role of Throwable class in Exception handling?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

ClassNotFoundException and NoClassDefFoundError are the errors when JVM or ClassLoader not able to find appropriate class while loading at run-time. ClassNotFoundException is a checked exception and NoClassDefFoundError is an Error which comes under unchecked.

</blockquote>

</details>

---

12.Why should we clean up activities such as i/o resources in the finally block?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

finally is useful for more than just exception handling — it allows the programmer to avoid having cleanup code accidentally bypassed by a return, continue, or break. Putting cleanup code in a finally block is always a good practice, even when no exceptions are anticipated.

</blockquote>

</details>

---

13.Consider three statements in a 'try' block: statement1, statement2, and statement3. It is followed by a 'catch' block to catch the exceptions that occurred during the execution of the 'try' block. Assume that the exception is thrown at statement2. Do you think the statement3 will be executed?  

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

Statement3 will not be executed. If an exception is thrown by the ‘try’ block at any point, the remaining code after the exception will not be executed. Instead, the flow control will directly come to the 'catch' block.

</blockquote>

</details>

---


14.When should we use the printStackTrace() method?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

printStackTrace() is very useful in diagnosing exceptions. For example, if one out of three methods in your code cause an exception, printStackTrace() will pinpoint the exact line in which the method raised the exception.

</blockquote>

</details>

---

15.Write the missing code in the give code block ?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<blockquote>
  
```java

public class Arithmetic {
public static void main(String args[]) {
	int d, a;
	try { 
		d = 0;
		a = 42 / d;
		} 
//write the missing code
}
}

```

</blockquote>
<details><summary><b> Show Answer</b></summary>

<blockquote>

```java

catch (ArithmeticException e) { 
System.out.println("Division by zero.");
}

```

</blockquote>

</details>

---

16.Define try-with resource. How can you say that it differs from an ordinary try?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

The try-with-resources statement is a try statement that declares one or more resources. The resource is as an object that must be closed after finishing the program. The try-with-resources statement ensures that each resource is closed at the end of the statement execution.You can pass any object that implements java.lang.AutoCloseable, which includes all objects which implement java.io.Closeable.The following example writes a string into a file. It uses an instance of FileOutputStream to write data into the file. FileOutputStream is a resource that must be closed after the program is finished with it. So, in this example, closing of resource is done by itself try.

```java 

import java.io.*;    

public class TryWithResources {    

public static void main(String args[]){    
  
try(FileOutputStream fileOutputStream =newFileOutputStream("/Textfiles/abc.txt")){    
  
String msg = "REVATURE!";      

byte byteArray[] = msg.getBytes(); 

fileOutputStream.write(byteArray);  

System.out.println("Message written to file successfuly!");  
    
}catch(Exception exception){  

       System.out.println(exception);  
}      
}      
}    

```

</blockquote>

</details>

---

17.Can we throw an exception explicitly or manually?explain with an example?

![Medium](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/Medium%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

we can throw a user defined exception or, a predefined exception explicitly using the throw keyword.There are two types of exceptions user defined and predefined each exception is represented by a class and which inherits the Throwable class.To throw an exception explicitly you need to instantiate the class of it and throw its object using the throw keyword.

```java

public class ExceptionExample {
   public static void main(String[] args) {
      System.out.println("Hello");
      NullPointerException nullPointer = new NullPointerException();
      throw nullPointer;
   }
}
Output
Hello
Exception in thread "main" java.lang.NullPointerException
   at MyPackage.ExceptionExample.main(ExceptionExample.java:6)

```

Whenever you throw an exception explicitly you need to make sure that the line with throw keyword is the last line of the program. This is because any code written after it is unreachable code and if you still have code snippets below this line a compile time error will be generated.

```java

Example
public class ExceptionExample {
   public static void main(String[] args) {
      System.out.println("Hello");
      NullPointerException nullPointer = new NullPointerException();
      throw nullPointer;
      System.out.println("How are you");
   }
}
Compile time error
D:\>javac ExceptionExample.java
ExceptionExample.java:6: error: unreachable statement
   System.out.println("How are you");
   ^
1 error

```

</blockquote>

</details>

---

18.Describe OutofMemoryError in exception handling?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

The OutofMemoryError  is thrown when there is insufficient space to allocate an object in the Java heap. In this case, The garbage collector cannot make space available to accommodate a new object, and the heap cannot be expanded further. Also, this error may be thrown when there is insufficient native memory to support the loading of a Java class. In a rare instance, a java.lang.OutOfMemoryError may be thrown when an excessive amount of time is being spent doing garbage collection and little memory is being freed.

</blockquote>

</details>

---

19.Explain with an example for  unchecked exception.

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

```java

class Example {  
   public static void main(String args[]) {
	try{
	   int arr[] ={1,2,3,4,5};
	   System.out.println(arr[7]);
	}
        catch(ArrayIndexOutOfBoundsException e){
System.out.println("The specified index does not exist " +"in array. Please correct the error.");
	}
   }
}

```
</blockquote>

</details>

---

20.Is it illegal to keep an empty catch?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

Yes, we can have an empty catch block. But this is a bad practice to implement in Java.The try block has the code which is capable of producing exceptions, if anything wrong in the try block, for instance, divide by zero, file not found, etc. It will generate an exception that is caught by the catch block. The catch block catches and handles the exception. If the catch block is empty then we will have no idea what went wrong within our code.
</blockquote>

</details>

---

21.Can checked exceptions occur at compiled time?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

A checked exception is an exception that occurs at the compile time, these are also called as compile time exceptions. These exceptions cannot simply be ignored at the time of compilation, the programmer should take care of (handle) these exceptions. For example, if you use FileReader class in your program to read data from a file, if the file specified in its constructor doesn't exist, then a FileNotFoundException occurs, and the compiler prompts the programmer to handle the exception.

</blockquote>

</details>

---

22.In which situation will you not be able to execute the finally block?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

We cannot say the finally block is always executes because sometimes if any statement like 
System.exit() or some similar code is written into try block then program will automatically terminate and the finally block will not be executed in this case.A finally block will not execute due to other conditions like when JVM runs out of memory when our java process is killed forcefully from task manager or console when our machine shuts down due to power failure and deadlock condition in our try block.

</blockquote>

</details>

---

23.Is it possible to throw a statement inside a static block?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

We cannot use throws keyword with a static block, and more over a static block is invoked at compile time (at the time of class loading) no method invokes it. If you throw an exception using the throw keyword in a static block you must wrap it within try-catch blocks else a compile time error will be generated.

</blockquote>

</details>

---

24.How rethrowing is done in exception handling?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

If a catch block cannot handle the particular exception it has caught, we can rethrow the exception. The rethrow expression causes the originally thrown object to be rethrown.Because the exception has already been caught at the scope in which the rethrow expression occurs, it is rethrown out to the next enclosing try block. Therefore, it cannot be handled by catch blocks at the scope in which the rethrow expression occurred. Any catch blocks for the enclosing try block have an opportunity to catch the exception.

```java

public class RethrowException {
   public static void test1() throws Exception {
      System.out.println("The Exception in test1() method");
      throw new Exception("thrown from test1() method");
   }
   public static void test2() throws Throwable {
      try {
         test1();
      } catch(Exception e) {
         System.out.println("Inside test2() method");
         throw e;
      }
   }
   public static void main(String[] args) throws Throwable {
      try {
         test2();
      } catch(Exception e) {
         System.out.println("Caught in main");
      }
   }
}

Output
The Exception in test1() method
Inside test2() method
Caught in main

```

</blockquote>

</details>

---

25.How can you handle a chained exception?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

The chained exception feature allows you to associate another exception with an exception. This second exception describes the cause of the first exception. For example,imagine a situation in which a method throws an ArithmeticException because of an attempt to divide by zero. However, the actual cause of the problem was that an I/O error occurred,which caused the divisor to be set improperly. Although the method must certainly throw an ArithmeticException, since that is the error that occurred, you might also want to let the calling code know that the underlying cause was an I/O error.

</blockquote>

</details>

---

26.Explain the methods in the throwable class.

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

  `Throwable fillInStackTrace ()`- Fills in the execution stack trace.
	
  `Throwable getCause ()` - Returns the cause of this throwable or null if the cause is nonexistent or unknown.
	
  `String getLocalizedMessage ()` - Creates a localized description of this throwable.
	
  `String getMessage ()` - Returns the detail message string of this throwable.
	
  `StackTraceElement []	getStackTrace ()` - Provides programmatic access to the stack trace information printed by printStackTrace() .
	
  `Throwable initCause ( Throwable  cause)` - Initializes the cause of this throwable to the specified value.
	
 `void printStackTrace ()` - Prints this throwable and its backtrace to the standard error stream.
	
 `void printStackTrace ( PrintStream  s)` - Prints this throwable and its backtrace to the specified print stream.
	
 `void printStackTrace ( PrintWriter  s)` - Prints this throwable and its backtrace to the specified print writer.
	
 `void setStackTrace ( StackTraceElement [] stackTrace)` - Sets the stack trace elements that will be returned by getStackTrace() and printed by printStackTrace() and related methods.
	
 `String toString ()` - Returns a short description of this throwable.

</blockquote>

</details>

---

27.When the unreachable catch block error is shown by the compiler?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

When you are keeping multiple catch blocks, the order of catch blocks must be from most specific to most general ones. i.e sub classes of Exception must come first and super classes later. If you keep super classes first and sub classes later, compiler will show unreachable catch block error.


public class ExceptionHandling
{
    public static void main(String[] args)
    {
        try
        {
            int i = Integer.parseInt("pqr");   //This statement throws NumberFormatException
        }
 
        catch(Exception e)
        {
            System.out.println("This block handles all exception types");
        }
 
        catch(NumberFormatException e)
        {
            //Compile time error
            //This block becomes unreachable as
            //exception is already caught by above catch block
        }
    }
}



</blockquote>

</details>

28.Why it is always recommended that clean up operations like closing the DB resources to keep inside a finally block?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

Because finally block is always executed whether exceptions are raised in the try block or not and raised exceptions are caught in the catch block or not. By keeping the clean up operations in finally block, you will ensure that those operations will be always executed irrespective of whether exception is occurred or not.

</blockquote>

</details>

---

29.Explain the difference between throw, throws and Throwable in java?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

throw :
throw is a keyword in java which is used to throw an exception manually. Using throw keyword, you can throw an exception from any method or block. But, that exception must be of type java.lang.Throwable class or it’s sub classes. 

```java

class ThrowExample
{
    void method() throws Exception
    {
        Exception e = new Exception();
 
        throw e;            //throwing an exception using 'throw'
    }
}

```

throws:
throws is also a keyword in java which is used in the method signature to indicate that this method may throw mentioned exceptions. The caller to such methods must handle the mentioned exceptions either using try-catch blocks or using throws keyword. 

```java

return_type method_name(parameter_list) throws exception_list
{
     //some statements
}

class ThrowsExample
{
    void methodOne() throws SQLException
    {
        //This method may throw SQLException
    }
 
    void methodTwo() throws IOException
    {
        //This method may throw IOException
    }
 
    void methodThree() throws ClassNotFoundException
    {
        //This method may throw ClassNotFoundException
    }
}

```

Throwable In Java :
Throwable is a super class for all types of errors and exceptions in java. This class is a member of java.lang package. Only instances of this class or it’s sub classes are thrown by the java virtual machine or by the throw statement. The only argument of catch block must be of this type or it’s sub classes. If you want to create your own customized exceptions, then your class must extend this class. 

```java

class MyException extends Throwable
{
           //Customized Exception class
}
 
class ThrowableExample
{
    void method() throws MyException
    {
        MyException e = new MyException();
 
        throw e;
    }
}

```

</blockquote>

</details>

---

30.Can we override a super class method which is throwing an unchecked exception with checked exception in the sub class?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

No. If a super class method is throwing an unchecked exception, then it can be overridden in the sub class with same exception or any other unchecked exceptions but can not be overridden with checked exceptions.

</blockquote>

</details>

---

31.What are the allowed combinations of try, catch and finally blocks in java?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

```java

try
{
    //try block
}
catch(Exception e)
{
    //catch block
}

try
{
    //try block
}
finally
{
    //finally block
}

try
{
    //try block
}
catch(Exception e)
{
    //catch block
}
finally
{
    //finally block
}

```

</blockquote>

</details>

---



