1.How can you throw an exception object for exception?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>
  
<blockquote>
  
The exception object contains a lot of debugging information such as method hierarchy, line number where the exception occurred, type of exception, etc. When the exception occurs in a method, the process of creating the exception object and handing it over to the runtime environment is called "throwing an  exception".Once runtime receives the exception object, it tries to find the handler for the exception. Exception Handler is the block of code that can process the exception object.

</blockquote>
  
</details>

---

2.Explain throw keyword with real time example?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>
we might want to generate exceptions explicitly in our code, for example in a user authentication program we should throw exceptions to clients if the password is null. The throw keyword is used to throw exceptions to the runtime to handle it.

</blockquote>
  
</details>

---

3.How the exception condition is created?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>
  
An object representing that exception is created and thrown in the method that caused the error. That method may choose to handle the exception itself, or pass it on. Either way, at some point, the exception is caught and processed. Exceptions can be generated by the Java run-time system, or they can be manually generated by your code.

</blockquote>
  
</details>

---

4.How exception handling manages try,catch,throw,throws and finally statements?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

Program statements that you want to monitor for exceptions are contained within a try block. If an exception occurs within the try block, it is thrown. The code can catch this exception using catch and handle it in some rational manner.System-generated exceptions are automatically thrown by the Java run-time system. To manually throw an exception, use the keyword throw. Any exception that is thrown out of a method must be specified as such by a throws clause. Any code that absolutely must be executed after a try block completes is put in a finally block.

</blockquote>

</details>

---

5.How the StackOverflow occurred?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

Error, which defines exceptions that are not expected to be caught under normal circumstances by your program. Exceptions of type Error are used by the Java run-time system to indicate errors having to do with the run-time environment,itself. Stack overflow is an example of such an error

</blockquote>

</details>

---

6.Can we keep other statements in between ‘try’, ‘catch’, and ‘finally’ blocks?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

It is not necessary to include any statements between the  ‘try’, ‘catch’, and ‘finally’ blocks, since they form one whole unit of the exception handling mechanism.

</blockquote>

</details>

---

7.Can we  include only a ‘try’ block without the ‘catch’ and ‘finally’ blocks?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

This would result in compilation error. It is necessary for the ‘try’ block to be followed with either a ‘catch’ block or a ‘finally’ block, if not both. Either one of ‘catch’ or ‘finally’ blocks is needed so that the flow of exception handling is undisrupted.

</blockquote>

</details>

---

8.What happens when you don’t handle exceptions in your program.

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

All exception types are subclasses of the built-in class Throwable. Thus, Throwable is at the top of the exception class hierarchy. Immediately below Throwable are two subclasses that partition exceptions into two distinct branches. One branch is headed by Exception. This class is used for exceptional conditions that user programs should catch. This is also the class that you will subclass to create your own custom exception types. There is an important subclass of Exception, called RuntimeException. Exceptions of this type are automatically defined for the programs that you write and include things such as division by zero and invalid array indexing.The other branch is topped by Error, which defines exceptions that are not expected to be caught under normal circumstances by your program. Exceptions of type Error are used by the Java run-time system to indicate errors having to do with the run-time environment,itself. Stack overflow is an example of such an error.


</blockquote>

</details>

---

9.Can we keep the statements after the ‘finally’ block?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

When the Java run-time system detects a runtime-error, it constructs a new exception object and then throws the exception because once an exception has been thrown, it must be caught by an exception handler and dealt with immediately. If we didn't supplied any exception handlers of our own, the exception is caught by the default handler provided by the Java run-time system. Any exception that is not caught by your program will ultimately be processed bythe default handler. The default handler describes the exception and prints a stack trace from the point at which the exception occurred, and terminates the program.

</blockquote>

</details>

---

10.How can you differentiate NoClassDefFoundError and ClassNotFoundException in Java?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

This will result in an unreachable catch block error. This is because the control will be returning from the 'finally' block itself. The compiler will fail to execute the code after the line with the exception. That is why the execution will show an unreachable code error.

</blockquote>

</details>

---

11.Explain the role of Throwable class in Exception handling?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

ClassNotFoundException and NoClassDefFoundError are the errors when JVM or ClassLoader not able to find appropriate class while loading at run-time. ClassNotFoundException is a checked exception and NoClassDefFoundError is an Error which comes under unchecked.

</blockquote>

</details>

---

12.Why should we clean up activities such as i/o resources in the finally block?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

finally is useful for more than just exception handling — it allows the programmer to avoid having cleanup code accidentally bypassed by a return, continue, or break. Putting cleanup code in a finally block is always a good practice, even when no exceptions are anticipated.

</blockquote>

</details>

---

13.Consider three statements in a 'try' block: statement1, statement2, and statement3. It is followed by a 'catch' block to catch the exceptions that occurred during the execution of the 'try' block. Assume that the exception is thrown at statement2. Do you think the statement3 will be executed?  

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

Statement3 will not be executed. If an exception is thrown by the ‘try’ block at any point, the remaining code after the exception will not be executed. Instead, the flow control will directly come to the 'catch' block.

</blockquote>

</details>

---


14.When should we use the printStackTrace() method?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<details><summary><b> Show Answer</b></summary>

<blockquote>

printStackTrace() is very useful in diagnosing exceptions. For example, if one out of three methods in your code cause an exception, printStackTrace() will pinpoint the exact line in which the method raised the exception.

</blockquote>

</details>

---

15.Write the missing code in the give code block ?

![Easy](https://github.com/revaturelabs/interviewquestions/blob/dev/ComplexityTags/simple%20(2).svg)

<blockquote>
  
```java

public class Arithmetic {
public static void main(String args[]) {
	int d, a;
	try { 
		d = 0;
		a = 42 / d;
		} 
//write the missing code
}
}

```

</blockquote>
<details><summary><b> Show Answer</b></summary>

<blockquote>

```java

catch (ArithmeticException e) { 
System.out.println("Division by zero.");
}

```

</blockquote>

</details>

---



